
modLoader="javafml" #mandatory

loaderVersion="[38,)"

license="All rights reserved"

[[mods]] #mandatory

modId="jeed" #mandatory

version="${file.jarVersion}" #mandatory

displayName="Just Enough Effect Descriptions" #mandatory

logoFile="icon.png" #optional

credits="MehVahdJukaar, Plantkillable" #optional

authors="MehVahdJukaar" #optional

itemIcon="minecraft:potion" #catalogue icon
description='''
A JEI plugin that displays all status effects and how to obtain them
'''

[[dependencies.jeed]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[38,)" #mandatory
    ordering="NONE"
    side="BOTH"

[[dependencies.jeed]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.0,1.19)"
    ordering="NONE"
    side="BOTH"

[[dependencies.jeed]]
    modId="jei"
    mandatory=false
    versionRange="[9.4.1.108,)"
    ordering="NONE"
    side="CLIENT"
